In [4]:
#lists
currencies = ["Dollar", "Euro", "yen","Pound "]
currencies.append("Rupee")
print(currencies)
currencies.extend(['Paisa','Dinar'])
print(currencies)

['Dollar', 'Euro', 'yen', 'Pound ', 'Rupee']
['Dollar', 'Euro', 'yen', 'Pound ', 'Rupee', 'Paisa', 'Dinar']


In [6]:
a1 = [1,2]
a2 = [3,4]
b = (3,4)
a1.extend(a2)
print(a1)
a2.extend(b)
print(a2)

[1, 2, 3, 4]
[3, 4, 3, 4]


In [8]:
n = [20,60,40,30]
max = n[0]
for i in n:
    if i>max:
        max = i
print(max)

60


In [14]:
m=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
for i in m:
    for j in i:
        print(j)
    print() #next line


1
2
3

4
5
6

7
8
9



In [22]:
#tuples
a = (1,1,2,3)
print(type(a))
for i in a:
    print(i)
print(a.count(1))
print(a.count(2))
b,c,d,e= a #unpacking
print(b)

<class 'tuple'>
1
1
2
3
2
1
1


In [25]:
s= "Hello World"
s1 = 'Anamika'
s3 = """Hey there, i'm Anamika
Welcome to Python programming""" #multiline string
print(s)
print(s1)   
print(s3)

#slicing
s[1:6] #start index is inclusive and end index is exclusive
print(s)


Hello World
Anamika
Hey there, i'm Anamika
Welcome to Python programming
Hello World


In [32]:
s = "ahsjnjajasjsa"
b = "hbjkiuhu"
print(s+"second"+b) #concatenation
n= "An"
m = "21"
print("My name is "+n+" and i am "+m+" years old") #string concatenation
print(f"My name is {n} and i am {m} years old") #f-string

ahsjnjajasjsasecondhbjkiuhu
My name is An and i am 21 years old
My name is An and i am 21 years old


In [36]:
animals = ["cat", "dog", "rabbit", "hamster"]
animals.remove("rabbit")
print(animals)
del animals[1]
print(animals)

['cat', 'dog', 'hamster']
['cat', 'hamster']


In [38]:
numbers = [1,2,3,4,5]
del numbers[2]
print(numbers)
del numbers[-1]
print(numbers)

[1, 2, 4, 5]
[1, 2, 4]


In [41]:
# multidimensional lists
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
for i in a:
    for j in i:
        print(j)
    print() #next line  

for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=" ") #end is used to print in the same line
    print() #next line

1
2
3

4
5
6

7
8
9

1 2 3 
4 5 6 
7 8 9 


In [42]:
m =4
n =5
a = [[0 for x in range(n)] for y in range(m) ] #creating a 2D list with 4 rows and 5 columns
print(a)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [51]:
#casefolding
text = ["Muzaffarpur", "Champapur", "Dholakpur", "Supaul"]
for i in text:
    if i.endswith("pur"):
        print(i)
textval="dhfsudbghspur sdndsdnspur sdmnspur dsndsmn"
result = textval.endswith("pur")
print(f"Text ends with 'pur': {result}")

Muzaffarpur
Champapur
Dholakpur
Text ends with 'pur': False


In [49]:
p = input("Enter a password:")
if len(p)<8:
    print("weak password")
elif not any(ch.isdigit() for ch in p):
    print("add atleast one digit")
elif not any(ch.isupper() for ch in p):
    print("add atleast one uppercase letter")
else:
    print("strong password")

weak password


In [54]:
import numpy as np
import time
import sys
SIZE = 1000000
L1 = range(SIZE)
L2 = range(SIZE)
A1=np.arange(SIZE)
A2=np.arange(SIZE)
start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)


139.05811309814453


In [61]:
import numpy as np
import time
s= time.time()
r = []
l= list(range(1000000))

for i in l:
    r.append(i**8)
e=time.time()
print("list time:", (e-s))

list time: 0.13586997985839844


In [59]:
a = np.arange(1000000)
s = time.time()
result = a**8
e = time.time()
print("numpy time:", (e-s))

numpy time: 0.002086162567138672


In [76]:
import numpy as np
a = np.array([1,2,4,5])
print(type(a))
b = np.array([[1,2],[3,4]])
print(type(b))
print(b.shape)
print(b.ndim)
print(b.dtype)
c= np.zeros((4,3))
print(c)
c= np.ones((2,5))
print(c)
c = np.arange(0,10,2)
print(c)
f = np.linspace(0,1000000245555,5) #start, end, number of elements
g = np.eye(4) #identity matrix of size 3x3
print(g)
print(f)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(2, 2)
2
int64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 2 4 6 8]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0.00000000e+00 2.50000061e+11 5.00000123e+11 7.50000184e+11
 1.00000025e+12]


In [80]:
d= np.full((3,3),6,dtype='complex')
print(d)
e=np.random.random((2,2))
print(e)
f=np.arange(0,30,5)
print(f)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
[[0.12386263 0.26274261]
 [0.13875048 0.9521982 ]]
[ 0  5 10 15 20 25]
